### PR TITLE
Resolve ASM type correctly

### LINKED ISSUE #220: Mapping to an array of Object throws a NullPointerException
Proof of Concept code at the bottom of the post.

When a custom PropertyMap has been defined for a given Source and Destination, and that Destination has a setter that accepts an array of Objects (`Object[]`), a NullPointerException is thrown.

The NPE is thrown in `org.modelmapper.internal.util.Primitive` when processing the map. `Primitives.primitiveFor` is called once, to process the array, and then a second time, with the type parameter of the array. However, calls to `Primitives.primtivesFor` with a Object return null explicitly. The null value is then used as the type in an attempt to construct a new Array instance.

**affected version:** 0.7.8
**stack trace**

    Caused by: java.lang.NullPointerException
    	at java.lang.reflect.Array.newInstance(Array.java:313)
    	at org.modelmapper.internal.util.Primitives.primitiveFor(Primitives.java:144)
    	at org.modelmapper.internal.ExplicitMappingVisitor.methodFor(ExplicitMappingVisitor.java:332)
    	at org.modelmapper.internal.ExplicitMappingVisitor.access$500(ExplicitMappingVisitor.java:35)
    	at org.modelmapper.internal.ExplicitMappingVisitor$MappingCapturingVisitor.visitEnd(ExplicitMappingVisit    or.java:200)
    	at org.modelmapper.internal.asm.ClassReader.b(Unknown Source)
    	at org.modelmapper.internal.asm.ClassReader.accept(Unknown Source)
    	at org.modelmapper.internal.asm.ClassReader.accept(Unknown Source)
    	at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:222)
    	at org.modelmapper.PropertyMap.configure(PropertyMap.java:380)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:88)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
    	at java.lang.reflect.Method.invoke(Method.java:613)
    	at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:195)

Proof of concept

    package modelmapper.test;
    
    import java.util.ArrayList;
    import java.util.List;
    
    import org.modelmapper.ModelMapper;
    import org.modelmapper.PropertyMap;
    
    public class ObjectArrayTest {
    
    	public static class CustomObject {
    		private String value;
    
    		public String getValue() {
    			return value;
    		}
    
    		public void setValue(String value) {
    			this.value = value;
    		}
    	}
    
    	public static class Source {
    		private List<CustomObject> objects;
    
    		public List<CustomObject> getObjects() {
    			return objects;
    		}
    
    		public void setObjects(List<CustomObject> objects) {
    			this.objects = objects;
    		}
    	}
    	
    	public static class Destination {
    		private CustomObject[] objects;
    
    		public CustomObject[] getObjects() {
    			return objects;
    		}
    
    		public void setObjects(CustomObject[] objects) {
    			this.objects = objects;
    		}
    	}
    	
    	public static void main (String[] args) {
    		ModelMapper mapper = new ModelMapper();
    		
    		Source source = new Source();
    		CustomObject obj = new CustomObject();
    		obj.setValue("value");
    		
    		List<CustomObject> objs = new ArrayList<CustomObject>();
    		objs.add(obj);
    		objs.add(obj);
    		objs.add(obj);
    		source.setObjects(objs);
    		
    		mapper.addMappings(new PropertyMap<Source, Destination>() {
    			@Override
    			protected void configure() {
    				map(source.getObjects()).setObjects(null);
    				
    			}
    		});
    		
    		Destination result = mapper.map(source, Destination.class);
    		mapper.validate();
    		
    		result.hashCode();
    	}
    
    }

### PR DESCRIPTION
**Pull request by chhsiao90**
Fixed ASM type resolver to resolve non-primitive array type correctly.

Resolved #220

### CODE REVIEW

File: core/src/main/java/org/modelmapper/internal/ExplicitMappingVisitor.java [hunk 1]
```diff
@@ -329,12 +330,41 @@ private Method methodFor(Class<?> type, Type methodType, MethodInsnNode mn) {
...
-      paramTypes[i] = paramType == null ? classFor(argumentTypes[i].getClassName()) : paramType;
+      paramTypes[i] = classFor(argumentTypes[i]);
     }
     return Members.methodFor(type, mn.name, paramTypes);
   }
 
+  /**
+   * Returns a origin class for the ASM {@code type}, else {@code null}.
+   */
+  public Class<?> classFor(Type type) {
```
Comment (jhalterman) [inline core/src/main/java/org/modelmapper/internal/ExplicitMappingVisitor.java]: See https://github.com/modelmapper/modelmapper/blob/master/core/src/main/java/org/modelmapper/internal/util/Primitives.java#L125

:)

Comment (chhsiao90) [inline core/src/main/java/org/modelmapper/internal/ExplicitMappingVisitor.java]: I moved this method to another place because it not only resolve for ```primitive``` type.
WDYT.

Comment (chhsiao90) [inline core/src/main/java/org/modelmapper/internal/ExplicitMappingVisitor.java]: Or maybe I can move it to https://github.com/modelmapper/modelmapper/blob/master/core/src/main/java/org/modelmapper/internal/util/Types.java ?

Comment (jhalterman) [inline core/src/main/java/org/modelmapper/internal/ExplicitMappingVisitor.java]: That makes sense. Maybe put it in util/Types then? The reasoning for that separation is single responsibility principle - converting types shouldn't be the responsibility of ExplicitMappingVisitor.

Comment (chhsiao90) [inline core/src/main/java/org/modelmapper/internal/ExplicitMappingVisitor.java]: Sure! I will have another commit for that, thanks for the suggestion.
